<style>body {margin:0; padding: 0;}</style>
<script src="https://www.google.com/jsapi"></script>
<?php $mapId = uniqid('map'); ?>
<script type="text/javascript">

        <?php if ($map == 'geochart') : ?>
        var options = {packages: ['geochart'], callback : drawMap<?php echo $mapId; ?>};
        <?php else: ?>
        var options = {packages: ['map'], callback : drawMap<?php echo $mapId; ?>};
        <?php endif; ?>
        google.load('visualization', '1', options);

        function drawMap<?php echo $mapId; ?>() {
            var options = <?php echo dts_json_encode($options); ?>;
            var data = google.visualization.arrayToDataTable(<?php echo dts_json_encode($values); ?>);

            <?php if ($map == 'geochart') : ?>
            var map = new google.visualization.GeoChart(document.getElementById('dts-map-<?php echo $mapId; ?>'));
            <?php else: ?>
            var map = new google.visualization.Map(document.getElementById('dts-map-<?php echo $mapId; ?>'));
            <?php endif; ?>
            map.draw(data, options);
        }
</script>

<div id="dts-map-<?php echo $mapId; ?>" style="width: <?php echo $mapData->width.(strpos($mapData->width,'%')?'':'px'); ?>; height: <?php echo $mapData->height; ?>px;"></div>