<?php $gridId = uniqid('grid'); ?>

<?php
    $currentBackground = 0;
    $maxBackground = count($backgrounds);
?>
<div id="<?php echo $gridId; ?>">
    <?php $i=0; foreach ($values as $value) : ?>
    <?php if ($i==0) : ?><div class="dts-grid-row dts-grid-row-<?php echo $options['columns_num']; ?>"><?php endif; ?>

    <?php
        if ($maxBackground) {
            if ($currentBackground>=$maxBackground) $currentBackground = 0;
            $background = $backgrounds[$currentBackground];
        } else {
            $background = '';
        }
    ?>
    <div class="dts-grid-column"><div class="dts-grid-column-content" style="background:<?php echo $background; ?>"><?php echo $value; ?></div></div>
    <?php $i++; ?>

    <?php if ($i==$options['columns_num']) : $i=0; ?></div><?php endif; ?>
    <?php $currentBackground++; ?>
<?php endforeach; ?>

<?php if (count($values) && $i && ($i<$options['columns_num'])) : ?></div><?php endif; ?>
</div>

<style>
    #<?php echo $gridId; ?> .dts-grid-row {
        margin-bottom: <?php echo $margin['bottom']; ?>px;
        margin-top: <?php echo $margin['top']; ?>px;
    }
    #<?php echo $gridId; ?> .dts-grid-column .dts-grid-column-content {
        padding-left: <?php echo $padding['left']; ?>px;
        padding-right: <?php echo $padding['right']; ?>px;
        padding-top: <?php echo $padding['top']; ?>px;
        padding-bottom: <?php echo $padding['bottom']; ?>px;

        border: <?php echo $border['size']; ?>px solid <?php echo $border['color']; ?>;
        border-radius: <?php echo $border['radius']; ?>px;

        margin-right: <?php echo $margin['horizontal']; ?>px;
     }
</style>