CREATE TABLE `wp_terms` (  `term_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,  `name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',  `slug` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',  `term_group` bigint(10) NOT NULL DEFAULT '0',  PRIMARY KEY (`term_id`),  KEY `slug` (`slug`(191)),  KEY `name` (`name`(191))) ENGINE=InnoDB AUTO_INCREMENT=76 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40000 ALTER TABLE `wp_terms` DISABLE KEYS */;
INSERT INTO `wp_terms` VALUES('1', 'Uncategorized', 'uncategorized', '0');
INSERT INTO `wp_terms` VALUES('5', 'apps', 'apps', '0');
INSERT INTO `wp_terms` VALUES('6', 'creativity', 'creativity', '0');
INSERT INTO `wp_terms` VALUES('7', 'design', 'design', '0');
INSERT INTO `wp_terms` VALUES('8', 'development', 'development', '0');
INSERT INTO `wp_terms` VALUES('9', 'ewfewfm', 'ewfewfm', '0');
INSERT INTO `wp_terms` VALUES('10', 'ewfwefwe', 'ewfwefwe', '0');
INSERT INTO `wp_terms` VALUES('11', 'fwefewf', 'fwefewf', '0');
INSERT INTO `wp_terms` VALUES('12', 'h', 'h', '0');
INSERT INTO `wp_terms` VALUES('13', 'hrt', 'hrt', '0');
INSERT INTO `wp_terms` VALUES('14', 'hrth', 'hrth', '0');
INSERT INTO `wp_terms` VALUES('15', 'interior', 'interior', '0');
INSERT INTO `wp_terms` VALUES('16', 'piracy', 'piracy', '0');
INSERT INTO `wp_terms` VALUES('17', 'rst', 'rst', '0');
INSERT INTO `wp_terms` VALUES('18', 'rt', 'rt', '0');
INSERT INTO `wp_terms` VALUES('19', 'rth', 'rth', '0');
INSERT INTO `wp_terms` VALUES('20', 'studio', 'studio', '0');
INSERT INTO `wp_terms` VALUES('21', 'technology', 'technology', '0');
INSERT INTO `wp_terms` VALUES('22', 'trhtrh', 'trhtrh', '0');
INSERT INTO `wp_terms` VALUES('23', 'wef', 'wef', '0');
INSERT INTO `wp_terms` VALUES('24', 'wefwef', 'wefwef', '0');
INSERT INTO `wp_terms` VALUES('25', 'apps', 'apps', '0');
INSERT INTO `wp_terms` VALUES('26', 'Branding', 'branding', '0');
INSERT INTO `wp_terms` VALUES('27', 'Downloads', 'downlaods', '0');
INSERT INTO `wp_terms` VALUES('28', 'ecommerce', 'ecommerce', '0');
INSERT INTO `wp_terms` VALUES('29', 'file_download', 'file_download', '0');
INSERT INTO `wp_terms` VALUES('30', 'font', 'font', '0');
INSERT INTO `wp_terms` VALUES('31', 'freebie', 'freebie', '0');
INSERT INTO `wp_terms` VALUES('32', 'gallery', 'gallery', '0');
INSERT INTO `wp_terms` VALUES('33', 'gateway_error', 'gateway_error', '0');
INSERT INTO `wp_terms` VALUES('34', 'Illustrations', 'illustrations', '0');
INSERT INTO `wp_terms` VALUES('35', 'Main', 'main-2', '0');
INSERT INTO `wp_terms` VALUES('36', 'packaged service', 'packaged-service', '0');
INSERT INTO `wp_terms` VALUES('37', 'photos', 'photos', '0');
INSERT INTO `wp_terms` VALUES('38', 'pictures', 'pictures', '0');
INSERT INTO `wp_terms` VALUES('39', 'plugins', 'plugins', '0');
INSERT INTO `wp_terms` VALUES('40', 'Recurrents', 'recurrents', '0');
INSERT INTO `wp_terms` VALUES('41', 'saas', 'saas', '0');
INSERT INTO `wp_terms` VALUES('42', 'sale', 'sale', '0');
INSERT INTO `wp_terms` VALUES('43', 'Tag1', 'tag1', '0');
INSERT INTO `wp_terms` VALUES('44', 'Tag2', 'tag2', '0');
INSERT INTO `wp_terms` VALUES('45', 'Tag3', 'tag3', '0');
INSERT INTO `wp_terms` VALUES('46', 'Tag4', 'tag4', '0');
INSERT INTO `wp_terms` VALUES('47', 'ui kit', 'ui-kit', '0');
INSERT INTO `wp_terms` VALUES('48', 'webfont', 'webfont', '0');
INSERT INTO `wp_terms` VALUES('49', 'wireframing', 'wireframing', '0');
INSERT INTO `wp_terms` VALUES('50', 'wordpress', 'wordpress', '0');
INSERT INTO `wp_terms` VALUES('51', 'Demo menu', 'demo-menu', '0');
INSERT INTO `wp_terms` VALUES('55', '信息披露', 'bulletin', '0');
INSERT INTO `wp_terms` VALUES('56', '基金产品', 'products', '0');
INSERT INTO `wp_terms` VALUES('61', '管理团队', 'team', '0');
INSERT INTO `wp_terms` VALUES('62', 'MY Login/Register', 'my-loginregister', '0');
INSERT INTO `wp_terms` VALUES('68', 'Blog', 'blog', '0');
INSERT INTO `wp_terms` VALUES('69', 'designing', 'designing', '0');
INSERT INTO `wp_terms` VALUES('70', 'Inner Page Left Menu', 'inner-page-left-menu', '0');
INSERT INTO `wp_terms` VALUES('71', 'Demo Menu (English)', 'demo-menu-english', '0');
INSERT INTO `wp_terms` VALUES('72', 'MY Login/Register - English', 'my-loginregister-english', '0');
INSERT INTO `wp_terms` VALUES('73', 'Inner Page Left Menu - English', 'inner-page-left-menu-english', '0');
INSERT INTO `wp_terms` VALUES('74', '知新1号信息披露', 'zhixin1', '0');
INSERT INTO `wp_terms` VALUES('75', '知新2号信息披露', 'zhixin2', '0');
/*!40000 ALTER TABLE `wp_terms` ENABLE KEYS */;
