<div class="wrap dts-form">

    <h2><?php echo esc_html( __( 'Add New Data Source', 'data-source' ) ); ?></h2>

    <form method="post" action="<?php echo $this->menuUrl('dts-sources', 'add'); ?>" id="dts-add-source-form">
        <input type="hidden" value="<?php echo $this->menuUrl('dts-sources', 'preview'); ?>" id="dts-load-preview-url" />
        <input type="hidden" value="<?php echo $this->menuUrl('dts-sources', 'checkDatabase'); ?>" id="dts-check-database-url" />
        <?php wp_nonce_field( 'dts-save-data-source'); ?>
        <div id="dts-add-source-form-container" class="metabox-holder">
            <div id="titlediv" class="dts-field-container">
                <input type="text" name="title" size="80" value="" id="title" spellcheck="true" autocomplete="off" placeholder="<?php esc_attr_e('Enter data source title', 'data-source'); ?>" />
            </div>
            <br class="clear" />
            <div id="dts-types-list" class="meta-box-sortables">
                <div class="postbox">
                    <div class="handlediv" title="<?php esc_html_e('Click to toggle', 'data-source'); ?>"><br></div>
                    <h3 class="hndle ui-sortable-handle"><span><?php esc_html_e('Data Source Type', 'data-source'); ?></span></h3>
                    <div class="inside">
                        <div class="pyre_metabox dts-field-container dts-type-options-container">
                            <label><input type="radio" name="type" value="mysql" data-container="mysql" /> <?php esc_html_e('MySQL table', 'data-source'); ?></label><br>
                            <label><input type="radio" name="type" value="csv" data-container="csv-file" /> <?php esc_html_e('CSV file', 'data-source'); ?> <i>(<?php esc_html_e('comma-separated values', 'data-source'); ?>)</i></label><br>
                            <label><input type="radio" name="type" value="xls" data-container="xls-file" /> <?php esc_html_e('Excel file', 'data-source'); ?> <i>(<?php esc_html_e('Microsoft Excel', 'data-source'); ?>)</i></label><br>
                            <label><input type="radio" name="type" value="xml" data-container="xml-file" /> <?php esc_html_e('XML file', 'data-source'); ?></label><br>
                            <label><input type="radio" name="type" value="google-spreadsheet" data-container="google-spreadsheet" /> <?php esc_html_e('Google Spreadsheet (old)', 'data-source'); ?></label><br>
                            <label><input type="radio" name="type" value="posts" data-container="posts" /> <?php esc_html_e('Wordpress Custom Posts', 'data-source'); ?></label>
                        </div>
                    </div>
                </div>
            </div>
            <div id="dts-mysql" class="dts-meta-box-container meta-box-sortables">
                <div class="postbox">
                    <div class="handlediv" title="<?php esc_html_e('Click to toggle', 'data-source'); ?>"><br></div>
                    <h3 class="hndle"><span><?php esc_html_e('MySQL table', 'data-source'); ?></span></h3>
                    <div class="inside">
                        <div class="field dts-field-container">
                            <label><input type="checkbox" name="mysql_custom" id="mysql-custom" value="1" /> <?php esc_html_e('Use another database', 'data-source'); ?></label>
                        </div>
                        <br>

                        <div id="dts-select-db-tab" style="display:none;">
                            <label for="mysql-host"><?php esc_html_e('Host (:port)', 'data-source'); ?></label>
                            <div class="field dts-field-container">
                                <input type="text" id="mysql-host" name="mysql_host" value="" />
                            </div>

                            <label for="mysql-user"><?php esc_html_e('User', 'data-source'); ?></label>
                            <div class="field dts-field-container">
                                <input type="text" id="mysql-user" name="mysql_user" value="" />
                            </div>

                            <label for="mysql-password"><?php esc_html_e('Password', 'data-source'); ?></label>
                            <div class="field dts-field-container">
                                <input type="text" id="mysql-password" name="mysql_password" value="" />
                            </div>

                            <label for="mysql-db"><?php esc_html_e('Database name', 'data-source'); ?></label>
                            <div class="field dts-field-container">
                                <input type="text" id="mysql-db" name="mysql_db" value="" />
                            </div>

                            <br>
                            <input type="button" value="<?php esc_attr_e('Set', 'data-source');?>" class="button check-db-btn">
                        </div>

                        <div id="dts-selected-db-tab">
                            <label for="mysql-table"><?php esc_html_e('Select Table', 'data-source'); ?></label>
                            <div class="field dts-field-container">
                                <select id="mysql-table-temp" style="display:none;">
                                    <option value=""><?php esc_html_e('[ Select Table ]', 'data-source'); ?></option>
                                    <option value="-1"><?php esc_html_e('-- Custom Query --', 'data-source'); ?></option>
                                    <?php foreach ($mysqlTables as $table) : ?>
                                        <option value="<?php echo esc_attr($table[0]); ?>"><?php echo esc_html($table[0]); ?></option>
                                    <?php endforeach; ?>
                                </select>
                                <select id="mysql-table" name="mysql_table">
                                    <option value=""><?php esc_html_e('[ Select Table ]', 'data-source'); ?></option>
                                    <option value="-1"><?php esc_html_e('-- Custom Query --', 'data-source'); ?></option>
                                    <?php foreach ($mysqlTables as $table) : ?>
                                    <option value="<?php echo esc_attr($table[0]); ?>"><?php echo esc_html($table[0]); ?></option>
                                    <?php endforeach; ?>
                                </select>
                                <input type="button" value="<?php esc_attr_e('Preview', 'data-source');?>" class="button preview-btn">
                            </div>
                            <div class="field dts-field-container">
                                <textarea cols="80" rows="10" id="mysql-query" name="mysql_query"></textarea>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div id="dts-csv-file" class="dts-meta-box-container meta-box-sortables">
                <div class="postbox">
                    <div class="handlediv" title="<?php esc_html_e('Click to toggle', 'data-source'); ?>"><br></div>
                    <h3 class="hndle"><span><?php esc_html_e('CSV file', 'data-source'); ?></span></h3>
                    <div class="inside">
                        <label for="upload-csv"><?php esc_html_e('Your file (URL or Upload)', 'data-source'); ?></label>
                        <div class="field dts-field-container">
                            <input type="text" id="upload-csv" name="csv_file" value="" size="50">
                            <input type="button" value="<?php esc_attr_e('Upload file', 'data-source');?>" class="button dts-upload" data-type="csv" data-target-field="upload-csv" data-dialog-title="<?php esc_attr_e('Upload CSV file', 'data-source');?>" data-button-text="<?php esc_attr_e('Use as Data Source', 'data-source');?>">
                            <input type="button" value="<?php esc_attr_e('Preview', 'data-source');?>" class="button preview-btn">
                        </div>
                    </div>
                </div>
            </div>

            <div id="dts-xls-file" class="dts-meta-box-container meta-box-sortables">
                <div class="postbox">
                    <div class="handlediv" title="<?php esc_html_e('Click to toggle', 'data-source'); ?>"><br></div>
                    <h3 class="hndle"><span><?php esc_html_e('Excel file', 'data-source');?></span></h3>
                    <div class="inside">
                        <label for="upload-xls"><?php esc_html_e('Your file (URL or Upload)', 'data-source');?></label>
                        <div class="field dts-field-container">
                            <input type="text" id="upload-xls" name="xls_file" value="" size="50">
                            <input type="button" value="<?php esc_attr_e('Upload file', 'data-source');?>" class="button dts-upload" data-type="xls" data-target-field="upload-xls" data-dialog-title="<?php esc_attr_e('Upload Excel file', 'data-source');?>" data-button-text="<?php esc_attr_e('Use as Data Source', 'data-source');?>">
                            <input type="button" value="<?php esc_attr_e('Preview', 'data-source');?>" class="button preview-btn">
                        </div>
                    </div>
                </div>
            </div>

            <div id="dts-xml-file" class="dts-meta-box-container meta-box-sortables">
                <div class="postbox">
                    <div class="handlediv" title="<?php esc_html_e('Click to toggle', 'data-source'); ?>"><br></div>
                    <h3 class="hndle"><span><?php esc_html_e('XML file', 'data-source');?></span></h3>
                    <div class="inside">
                        <label for="upload-xml"><?php esc_html_e('Your file (URL or Upload)', 'data-source');?></label>
                        <div class="field dts-field-container">
                            <input type="text" id="upload-xml" name="xml_file" value="" size="50">
                            <input type="button" value="<?php esc_attr_e('Upload file', 'data-source');?>" class="button dts-upload" data-type="xml" data-target-field="upload-xml" data-dialog-title="<?php esc_attr_e('Upload XML file', 'data-source');?>" data-button-text="<?php esc_attr_e('Use as Data Source', 'data-source');?>">
                            <input type="button" value="<?php esc_attr_e('Preview', 'data-source');?>" class="button preview-btn">
                        </div>

                        <label for="xml-parent-path"><?php esc_html_e('Select node for your items', 'data-source');?></label>
                        <div class="field dts-field-container">
                            <select id="xml-parent-path" name="xml_parent_path">
                                <option value=""><?php esc_html_e('[ XML root ]', 'data-source'); ?></option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>

            <div id="dts-google-spreadsheet" class="dts-meta-box-container meta-box-sortables">
                <div class="postbox">
                    <div class="handlediv" title="<?php esc_html_e('Click to toggle', 'data-source'); ?>"><br></div>
                    <h3 class="hndle"><span><?php esc_html_e('Google Spreadsheet', 'data-source');?></span></h3>
                    <div class="inside">
                        <label for="google-spreadsheet"><?php esc_html_e('URL to Google Spreadsheet', 'data-source');?></label>
                        <div class="field dts-field-container">
                            <input type="text" id="google-spreadsheet" name="google_spreadsheet" value="" size="50">
                            <input type="button" value="<?php esc_attr_e('Preview', 'data-source');?>" class="button preview-btn">
                            <p><?php esc_html_e('Please note, this feature exists for compatibility with old publishing method available for Google spreadsheets created before the August of 2015. As of today Google Spreadsheets allows publishing data as CSV files, please do so and use CSV file method', 'data-source'); ?></p>
                            <p><?php esc_html_e('Your spreadsheet should published. You can turn this feature on by following these steps:', 'data-source'); ?></p>
                            <p><?php esc_html_e('1. Open the document or spreadsheet.', 'data-source'); ?></p>
                            <p><?php esc_html_e('2. Go to the File menu.', 'data-source'); ?></p>
                            <p><?php esc_html_e('3. Select Publish to the Web.', 'data-source'); ?></p>
                            <p><?php esc_html_e('4. Click Published content & settings.', 'data-source'); ?></p>
                            <p><?php esc_html_e('Check the box next to "Automatically republish when changes are made" to allow changes to be updated in the published version.', 'data-source'); ?></p>
                        </div>
                    </div>
                </div>
            </div>

            <div id="dts-posts" class="dts-meta-box-container meta-box-sortables">
                <div class="postbox">
                    <div class="handlediv" title="<?php esc_html_e('Click to toggle', 'data-source'); ?>"><br></div>
                    <h3 class="hndle"><span><?php esc_html_e('Wordpress Posts', 'data-source');?></span></h3>
                    <div class="inside">
                        <label for="wordpress-post-type"><?php esc_html_e('Wordpress Posts', 'data-source');?></label>
                        <div class="field dts-field-container">
                            <select id="wordpress-post-type" name="wordpress_post_type">
                                <option value=""><?php esc_html_e('[ Select Post Type ]', 'data-source'); ?></option>
                                <?php foreach ($postTypes as $postType) : ?>
                                    <option value="<?php echo esc_attr($postType); ?>"><?php echo esc_html($postType); ?></option>
                                <?php endforeach; ?>
                            </select>
                            <input type="button" value="<?php esc_attr_e('Preview', 'data-source');?>" class="button preview-btn">
                            <p><?php esc_html_e('All custom post types registered within your Wordpress installation are displayed above', 'data-source'); ?></p>
                        </div>
                    </div>
                </div>
            </div>

            <div id="dts-preview" class="dts-meta-box-container meta-box-sortables">
                <div class="postbox">
                    <div class="handlediv" title="<?php esc_html_e('Click to toggle', 'data-source'); ?>"><br></div>
                    <h3 class="hndle"><span><?php esc_html_e('Data Source Preview', 'data-source');?></span></h3>
                    <div class="inside"></div>
                </div>
            </div>

            <div class="save-data-source-form">
                <input type="submit" class="button-primary" name="save" value="<?php echo esc_attr( __( 'Save', 'data-source' ) ); ?>" />
            </div>
        </div>
    </form>
</div>